apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-jiva
  annotations:
    cas.openebs.io/config: |
      - name: FSType
        value: "xfs"
      - name: ReplicaCount
        value: "1"        
provisioner: openebs.io/provisioner-iscsi