---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: te
  labels:
    app: nuodb
    group: nuodb
    deploymentconfig: te
    type: workload
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: te
        deploymentconfig: te
        database: nuodb
        nodetype: te
        type: workload
    spec:
      containers:
      -
        name: te
        image: nuodb/nuodb-ce:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - { name: DB_NAME,             value: "nuodb" }
        - { name: NUOCMD_API_SERVER,   value: "admin.nuodb-cstor.svc:8888"}
        - { name: PEER_ADDRESS,        value: "admin.nuodb-cstor.svc" }
        - { name: NUODB_LABELS,        value: "" }
        - { name: NUODB_OPTIONS,       value: "mem 1g" }
        args: [ "nuote", "--servers-ready-timeout", "300", "--database-created-timeout", "300" ]
        ports:
        - containerPort: 48006
          protocol: TCP
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
            - mountPath: /var/log/nuodb
              name: demo-vol1
      volumes:
        - name: demo-vol1
          persistentVolumeClaim:
            claimName: nuodb-cstor-demo-vol1-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nuodb-cstor-demo-vol1-claim
spec:
  storageClassName: ci-ssd-pool
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
