---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: wordpress-nfs
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wordpress-nfs
  labels:
    app: wordpress-sql
    type: workload
spec:
  selector:
    matchLabels:
      app: wordpress-sql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-sql
        tier: mysql
        type: workload
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: w0rdPres5
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-sql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-sql-pvc
  namespace: wordpress-nfs
  labels:
    app: wordpress
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
