apiVersion: v1
kind: ServiceAccount
metadata:
  name: percona-cstor-user-service-account
  namespace: percona-cstor
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: user-privilege-role
rules:
- apiGroups: ["*"]
  resources: ["cstorvolumes", "events"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: percona-cstor-user-service-account
  namespace: percona-cstor
subjects:
- kind: ServiceAccount
  name: percona-cstor-user-service-account
  namespace: percona-cstor
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:percona-cstor:percona-cstor
roleRef:
  kind: ClusterRole
  name: user-privilege-role
  apiGroup: rbac.authorization.k8s.io
