apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-cstor-user-service-account
  namespace: mongo-cstor
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: user-privilege-role
rules:
- apiGroups: ["*"]
  resources: ["cstorvolumes", "events"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-cstor-user-service-account
  namespace: mongo-cstor
subjects:
- kind: ServiceAccount
  name: mongo-cstor-user-service-account
  namespace: mongo-cstor
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:mongo-cstor:mongo-cstor
roleRef:
  kind: ClusterRole
  name: user-privilege-role
  apiGroup: rbac.authorization.k8s.io
